//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaVisual_Login.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VCARONIBD1\\VCARONIBD1;Initial Catalog=BD013;User ID=interconexion")]
        public string BD013ConnectionString {
            get {
                return ((string)(this["BD013ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=vcaronibd1\\vcaronibd1;Initial Catalog=BD_098_04_04_2024;Persist Secur" +
            "ity Info=True;User ID=interconexion;Password=interconexion")]
        public string BD_098_04_04_2024ConnectionString {
            get {
                return ((string)(this["BD_098_04_04_2024ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=vcaronibd1\\vcaronibd1;Initial Catalog=BD_151_2024;Persist Security In" +
            "fo=True;User ID=interconexion;Password=interconexion")]
        public string BD_151_2024ConnectionString {
            get {
                return ((string)(this["BD_151_2024ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=vcaronibd1\\vcaronibd1;Initial Catalog=BD_107_Epos2;Persist Security I" +
            "nfo=True;User ID=interconexion;Password=interconexion")]
        public string BD_107_Epos2ConnectionString {
            get {
                return ((string)(this["BD_107_Epos2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=vcaronibd1\\vcaronibd1;Initial Catalog=BD095;Persist Security Info=Tru" +
            "e;User ID=interconexion")]
        public string BD095ConnectionString {
            get {
                return ((string)(this["BD095ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=vcaronibd1\\vcaronibd1;Initial Catalog=BD122JR;User ID=interconexion;P" +
            "assword=interconexion")]
        public string BD122JRConnectionString {
            get {
                return ((string)(this["BD122JRConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=vcaronibd1\\vcaronibd1;Initial Catalog=BD125EJ;Persist Security Info=T" +
            "rue;User ID=interconexion;Password=interconexion")]
        public string BD125EJConnectionString {
            get {
                return ((string)(this["BD125EJConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=vcaronibd1\\vcaronibd1;Initial Catalog=BD018FB;User ID=interconexion;P" +
            "assword=interconexion")]
        public string BD018FBConnectionString {
            get {
                return ((string)(this["BD018FBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=vcaronibd1\\vcaronibd1;Initial Catalog=BD117FB;User ID=interconexion;P" +
            "assword=interconexion")]
        public string BD117FBConnectionString {
            get {
                return ((string)(this["BD117FBConnectionString"]));
            }
        }
    }
}
